-- Northern Peptides Products Table
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  category VARCHAR(100) NOT NULL,
  description TEXT,
  description_short TEXT,
  benefits TEXT,
  mechanism TEXT,
  price DECIMAL(10, 2) NOT NULL,
  stock_qty INTEGER DEFAULT 0,
  strength VARCHAR(50),
  form VARCHAR(100),
  image_url TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_products_active ON products(active);

-- Enable RLS
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Allow public read access to products
CREATE POLICY "Products are viewable by everyone" ON products
  FOR SELECT USING (true);

-- Insert all products
INSERT INTO products (name, slug, category, description, description_short, benefits, mechanism, price, stock_qty, strength, form) VALUES
('5-Amino 10mg', '5-amino-10mg', 'Weight Loss / Metabolic', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways. May support fat loss, metabolic health, and body recomposition in research settings. Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways.', 'May support fat loss, metabolic health, and body recomposition in research settings.', 'Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 57, 0, '10mg', 'Lyophilized powder / Injectable'),
('5-Amino 50mg', '5-amino-50mg', 'Weight Loss / Metabolic', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways. May support fat loss, metabolic health, and body recomposition in research settings. Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways.', 'May support fat loss, metabolic health, and body recomposition in research settings.', 'Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 143, 0, '50mg', 'Lyophilized powder / Injectable'),
('5-Amino 5mg', '5-amino-5mg', 'Weight Loss / Metabolic', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways. May support fat loss, metabolic health, and body recomposition in research settings. Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways.', 'May support fat loss, metabolic health, and body recomposition in research settings.', 'Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 57, 0, '5mg', 'Lyophilized powder / Injectable'),
('ACE-031 1mg', 'ace-031-1mg', 'Bodybuilding / Fitness', 'A myostatin inhibitor peptide. Promotes muscle growth, strength enhancement, potential in muscle-wasting diseases. Blocks myostatin, a protein that inhibits muscle development.', 'A myostatin inhibitor peptide.', 'Promotes muscle growth, strength enhancement, potential in muscle-wasting diseases.', 'Blocks myostatin, a protein that inhibits muscle development.', 130, 0, '1mg', 'Lyophilized powder / Injectable'),
('Adipotide 10mg', 'adipotide-10mg', 'Weight Loss / Metabolic', 'ADIPOTIDE is a research peptide used in advanced protocols. It is explored for potential benefits in performance, recovery, and metabolic support. Its mechanisms are still being studied and it should be considered for research use only.', 'ADIPOTIDE is a research peptide used in advanced protocols.', 'It is explored for potential benefits in performance, recovery, and metabolic support.', 'Its mechanisms are still being studied and it should be considered for research use only.', 60, 0, '10mg', 'Lyophilized powder / Injectable'),
('AICAR 50mg', 'aicar-50mg', 'Weight Loss / Metabolic', 'An AMP-activated protein kinase (AMPK) activator. Mimics exercise effects, enhances endurance, supports fat metabolism. Activates AMPK, promoting glucose uptake and fatty acid oxidation.', 'An AMP-activated protein kinase (AMPK) activator.', 'Mimics exercise effects, enhances endurance, supports fat metabolism.', 'Activates AMPK, promoting glucose uptake and fatty acid oxidation.', 150, 0, '50mg', 'Lyophilized powder / Injectable'),
('AOD9604 10mg', 'aod9604-10mg', 'Weight Loss / Metabolic', 'Fragment of human growth hormone. Fat burning, weight management, supports cartilage repair. Stimulates lipolysis without significantly affecting blood sugar or growth.', 'Fragment of human growth hormone.', 'Fat burning, weight management, supports cartilage repair.', 'Stimulates lipolysis without significantly affecting blood sugar or growth.', 71, 0, '10mg', 'Lyophilized powder / Injectable'),
('AOD9604 5mg', 'aod9604-5mg', 'Weight Loss / Metabolic', 'Fragment of human growth hormone. Fat burning, weight management, supports cartilage repair. Stimulates lipolysis without significantly affecting blood sugar or growth.', 'Fragment of human growth hormone.', 'Fat burning, weight management, supports cartilage repair.', 'Stimulates lipolysis without significantly affecting blood sugar or growth.', 43, 0, '5mg', 'Lyophilized powder / Injectable'),
('ARA-290 10mg', 'ara-290-10mg', 'General Health', 'A peptide analog of erythropoietin-derived sequences with tissue-protective properties. Investigated for neuropathic pain relief, anti-inflammatory effects, and organ protection. Acts on the innate repair receptor (IRR), modulating inflammatory signaling and promoting tissue repair without stimulating red blood cell production.', 'A peptide analog of erythropoietin-derived sequences with tissue-protective properties.', 'Investigated for neuropathic pain relief, anti-inflammatory effects, and organ protection.', 'Acts on the innate repair receptor (IRR), modulating inflammatory signaling and promoting tissue repair without stimulating red blood cell production.', 50, 0, '10mg', 'Lyophilized powder / Injectable'),
('BPC+ TB500 10mg', 'bpc-tb500-10mg', 'Healing / Recovery', 'A combination of BPC-157 and TB-500 formulated for intensive healing support. Used in research for accelerated recovery from soft-tissue injuries, tendon and ligament support, and reduced inflammation. Combines angiogenesis- and cell-migration–supporting pathways of both peptides to enhance tissue regeneration.', 'A combination of BPC-157 and TB-500 formulated for intensive healing support.', 'Used in research for accelerated recovery from soft-tissue injuries, tendon and ligament support, and reduced inflammation.', 'Combines angiogenesis- and cell-migration–supporting pathways of both peptides to enhance tissue regeneration.', 68, 0, '10mg', 'Lyophilized powder / Injectable'),
('BPC+ TB500 20mg', 'bpc-tb500-20mg', 'Healing / Recovery', 'A combination of BPC-157 and TB-500 formulated for intensive healing support. Used in research for accelerated recovery from soft-tissue injuries, tendon and ligament support, and reduced inflammation. Combines angiogenesis- and cell-migration–supporting pathways of both peptides to enhance tissue regeneration.', 'A combination of BPC-157 and TB-500 formulated for intensive healing support.', 'Used in research for accelerated recovery from soft-tissue injuries, tendon and ligament support, and reduced inflammation.', 'Combines angiogenesis- and cell-migration–supporting pathways of both peptides to enhance tissue regeneration.', 107, 0, '20mg', 'Lyophilized powder / Injectable'),
('BPC-157 10mg', 'bpc-157-10mg', 'Healing / Recovery', 'A synthetic peptide derived from gastric proteins. Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health. Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 'A synthetic peptide derived from gastric proteins.', 'Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health.', 'Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 57, 0, '10mg', 'Lyophilized powder / Injectable'),
('BPC-157 20mg', 'bpc-157-20mg', 'Healing / Recovery', 'A synthetic peptide derived from gastric proteins. Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health. Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 'A synthetic peptide derived from gastric proteins.', 'Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health.', 'Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 98, 0, '20mg', 'Lyophilized powder / Injectable'),
('BPC-157 5mg', 'bpc-157-5mg', 'Healing / Recovery', 'A synthetic peptide derived from gastric proteins. Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health. Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 'A synthetic peptide derived from gastric proteins.', 'Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health.', 'Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 32, 0, '5mg', 'Lyophilized powder / Injectable'),
('Cagrilintide 2.4mg', 'cagrilintide-2-4mg', 'Weight Loss / Metabolic', 'Amylin analog developed for obesity management. Weight loss, appetite control, metabolic health improvement. Activates amylin receptors, enhancing satiety and glucose regulation.', 'Amylin analog developed for obesity management.', 'Weight loss, appetite control, metabolic health improvement.', 'Activates amylin receptors, enhancing satiety and glucose regulation.', 120, 0, '2.4mg', 'Lyophilized powder / Injectable'),
('CJC-1295 with DAC 5mg', 'cjc-1295-with-dac-5mg', 'Bodybuilding / Fitness', 'A long-acting synthetic analog of growth hormone-releasing hormone (GHRH). Provides stable GH release over days, improves recovery, supports lean muscle growth, enhances fat metabolism. Binds to pituitary receptors and maintains prolonged GH release due to Drug Affinity Complex (DAC) technology.', 'A long-acting synthetic analog of growth hormone-releasing hormone (GHRH).', 'Provides stable GH release over days, improves recovery, supports lean muscle growth, enhances fat metabolism.', 'Binds to pituitary receptors and maintains prolonged GH release due to Drug Affinity Complex (DAC) technology.', 54, 0, '5mg', 'Lyophilized powder / Injectable'),
('CJC-1295 without DAC + IPA 5mg', 'cjc-1295-without-dac-ipa-5mg', 'Bodybuilding / Fitness', 'A synergistic blend of CJC-1295 and Ipamorelin. Maximizes GH secretion, enhances recovery, supports lean mass gain, fat burning, and cellular repair. CJC-1295 stimulates GH release while Ipamorelin selectively enhances it without significant cortisol increase.', 'A synergistic blend of CJC-1295 and Ipamorelin.', 'Maximizes GH secretion, enhances recovery, supports lean mass gain, fat burning, and cellular repair.', 'CJC-1295 stimulates GH release while Ipamorelin selectively enhances it without significant cortisol increase.', 57, 0, '5mg', 'Lyophilized powder / Injectable'),
('CJC-1295 without DAC 5mg', 'cjc-1295-without-dac-5mg', 'Bodybuilding / Fitness', 'A shorter-acting version of CJC-1295, also a GHRH analog. Stimulates natural GH release in a pulsatile manner, supports muscle growth and fat loss, improves sleep quality. Triggers pituitary GH release but with a shorter half-life, mimicking natural hormone rhythms.', 'A shorter-acting version of CJC-1295, also a GHRH analog.', 'Stimulates natural GH release in a pulsatile manner, supports muscle growth and fat loss, improves sleep quality.', 'Triggers pituitary GH release but with a shorter half-life, mimicking natural hormone rhythms.', 50, 0, '5mg', 'Lyophilized powder / Injectable'),
('DSIP 5mg', 'dsip-5mg', 'Cognitive / Focus', 'Delta Sleep-Inducing Peptide. Improves sleep quality, reduces stress, supports hormone regulation. Regulates sleep-wake cycles and influences pituitary hormone release.', 'Delta Sleep-Inducing Peptide.', 'Improves sleep quality, reduces stress, supports hormone regulation.', 'Regulates sleep-wake cycles and influences pituitary hormone release.', 35, 0, '5mg', 'Lyophilized powder / Injectable'),
('Epithalon 10mg', 'epithalon-10mg', 'Anti-Aging / Beauty', 'A synthetic peptide linked to anti-aging research. May extend lifespan, supports telomere length, improves sleep regulation. Increases telomerase activity and regulates melatonin production.', 'A synthetic peptide linked to anti-aging research.', 'May extend lifespan, supports telomere length, improves sleep regulation.', 'Increases telomerase activity and regulates melatonin production.', 36, 0, '10mg', 'Lyophilized powder / Injectable'),
('Epithalon 50mg', 'epithalon-50mg', 'Anti-Aging / Beauty', 'A synthetic peptide linked to anti-aging research. May extend lifespan, supports telomere length, improves sleep regulation. Increases telomerase activity and regulates melatonin production.', 'A synthetic peptide linked to anti-aging research.', 'May extend lifespan, supports telomere length, improves sleep regulation.', 'Increases telomerase activity and regulates melatonin production.', 68, 0, '50mg', 'Lyophilized powder / Injectable'),
('Follistatin-344 5mg', 'follistatin-344-5mg', 'Bodybuilding / Fitness', 'Myostatin inhibitor protein fragment. Promotes muscle hypertrophy, potential in muscle-wasting conditions. Binds to and inhibits myostatin and activins.', 'Myostatin inhibitor protein fragment.', 'Promotes muscle hypertrophy, potential in muscle-wasting conditions.', 'Binds to and inhibits myostatin and activins.', 289, 0, '5mg', 'Lyophilized powder / Injectable'),
('GHK-CU 100mg', 'ghk-cu-100mg', 'Anti-Aging / Beauty', 'A naturally occurring copper-binding peptide. Promotes skin repair, reduces wrinkles, stimulates hair growth, accelerates wound healing. Stimulates collagen and glycosaminoglycan synthesis, modulates gene expression related to repair.', 'A naturally occurring copper-binding peptide.', 'Promotes skin repair, reduces wrinkles, stimulates hair growth, accelerates wound healing.', 'Stimulates collagen and glycosaminoglycan synthesis, modulates gene expression related to repair.', 71, 0, '100mg', 'Lyophilized powder / Injectable'),
('GHK-CU 50mg', 'ghk-cu-50mg', 'Anti-Aging / Beauty', 'A naturally occurring copper-binding peptide. Promotes skin repair, reduces wrinkles, stimulates hair growth, accelerates wound healing. Stimulates collagen and glycosaminoglycan synthesis, modulates gene expression related to repair.', 'A naturally occurring copper-binding peptide.', 'Promotes skin repair, reduces wrinkles, stimulates hair growth, accelerates wound healing.', 'Stimulates collagen and glycosaminoglycan synthesis, modulates gene expression related to repair.', 39, 0, '50mg', 'Lyophilized powder / Injectable'),
('GLOW 70mg', 'glow-70mg', 'Anti-Aging / Beauty', 'Peptide blend for skin and tissue health. Skin rejuvenation, collagen stimulation, improved elasticity. Promotes fibroblast activity and collagen synthesis.', 'Peptide blend for skin and tissue health.', 'Skin rejuvenation, collagen stimulation, improved elasticity.', 'Promotes fibroblast activity and collagen synthesis.', 129, 0, '70mg', 'Lyophilized powder / Injectable'),
('Glutathione 1500mg', 'glutathione-1500mg', 'Anti-Aging / Beauty', 'A powerful endogenous antioxidant. Detoxification, immune support, skin brightening, anti-aging effects. Neutralizes free radicals and supports liver detox pathways.', 'A powerful endogenous antioxidant.', 'Detoxification, immune support, skin brightening, anti-aging effects.', 'Neutralizes free radicals and supports liver detox pathways.', 107, 0, '1500mg', 'Lyophilized powder / Injectable'),
('HCG 5000 IU', 'hcg-5000-iu', 'Hormonal / Fertility', 'Human chorionic gonadotropin is a peptide hormone used in hormone support protocols. In research and clinical settings it supports testosterone production, fertility, and preservation of testicular function. Mimics luteinizing hormone (LH) at the testes, stimulating natural steroidogenesis.', 'Human chorionic gonadotropin is a peptide hormone used in hormone support protocols.', 'In research and clinical settings it supports testosterone production, fertility, and preservation of testicular function.', 'Mimics luteinizing hormone (LH) at the testes, stimulating natural steroidogenesis.', 50, 0, '5000 IU', 'Lyophilized powder / Injectable'),
('IGF-1LR3 1mg', 'igf-1lr3-1mg', 'Bodybuilding / Fitness', 'A long-acting analog of insulin-like growth factor 1 (IGF-1). Studied for enhanced muscle growth, recovery, and nutrient partitioning. Extends IGF-1 activity time in circulation, activating IGF-1 receptors involved in muscle hypertrophy and repair.', 'A long-acting analog of insulin-like growth factor 1 (IGF-1).', 'Studied for enhanced muscle growth, recovery, and nutrient partitioning.', 'Extends IGF-1 activity time in circulation, activating IGF-1 receptors involved in muscle hypertrophy and repair.', 61, 0, '1mg', 'Lyophilized powder / Injectable'),
('Ipamorelin 10mg', 'ipamorelin-10mg', 'Bodybuilding / Fitness', 'A selective growth hormone secretagogue. Promotes muscle growth, recovery, fat reduction, improved sleep. Stimulates GH release without affecting cortisol or prolactin significantly.', 'A selective growth hormone secretagogue.', 'Promotes muscle growth, recovery, fat reduction, improved sleep.', 'Stimulates GH release without affecting cortisol or prolactin significantly.', 64, 0, '10mg', 'Lyophilized powder / Injectable'),
('Ipamorelin 5mg', 'ipamorelin-5mg', 'Bodybuilding / Fitness', 'A selective growth hormone secretagogue. Promotes muscle growth, recovery, fat reduction, improved sleep. Stimulates GH release without affecting cortisol or prolactin significantly.', 'A selective growth hormone secretagogue.', 'Promotes muscle growth, recovery, fat reduction, improved sleep.', 'Stimulates GH release without affecting cortisol or prolactin significantly.', 36, 0, '5mg', 'Lyophilized powder / Injectable'),
('KissPeptin-10 10mg', 'kisspeptin-10-10mg', 'Hormonal / Fertility', 'Peptide involved in reproductive health. Stimulates fertility, regulates puberty and reproductive hormones. Activates GnRH release in the hypothalamus.', 'Peptide involved in reproductive health.', 'Stimulates fertility, regulates puberty and reproductive hormones.', 'Activates GnRH release in the hypothalamus.', 68, 0, '10mg', 'Lyophilized powder / Injectable'),
('KLOW 10mg', 'klow-10mg', 'Bodybuilding / Fitness', 'Research peptide formulation. Supports recovery, metabolism, and muscle health (emerging research). Likely acts via metabolic and growth-regulating pathways.', 'Research peptide formulation.', 'Supports recovery, metabolism, and muscle health (emerging research).', 'Likely acts via metabolic and growth-regulating pathways.', 157, 0, '10mg', 'Lyophilized powder / Injectable'),
('KPV 10mg', 'kpv-10mg', 'General Health', 'KPV is a research peptide used in advanced wellness protocols. It is explored for potential benefits in performance, recovery, and overall vitality. Its exact mechanisms are still being investigated and it should be used for research purposes only.', 'KPV is a research peptide used in advanced wellness protocols.', 'It is explored for potential benefits in performance, recovery, and overall vitality.', 'Its exact mechanisms are still being investigated and it should be used for research purposes only.', 57, 0, '10mg', 'Lyophilized powder / Injectable'),
('LL-37 5mg', 'll-37-5mg', 'General Health', 'An antimicrobial peptide from the innate immune system. Supports immune defense, wound healing, anti-inflammatory effects. Disrupts bacterial membranes and modulates immune response.', 'An antimicrobial peptide from the innate immune system.', 'Supports immune defense, wound healing, anti-inflammatory effects.', 'Disrupts bacterial membranes and modulates immune response.', 86, 0, '5mg', 'Lyophilized powder / Injectable'),
('MGF 2mg', 'mgf-2mg', 'Bodybuilding / Fitness', 'Mechano Growth Factor, a splice variant of IGF-1. Promotes muscle repair and growth after exercise. Activates satellite cells and muscle regeneration pathways.', 'Mechano Growth Factor, a splice variant of IGF-1.', 'Promotes muscle repair and growth after exercise.', 'Activates satellite cells and muscle regeneration pathways.', 71, 0, '2mg', 'Lyophilized powder / Injectable'),
('MOTS-C 10mg', 'mots-c-10mg', 'Weight Loss / Metabolic', 'A mitochondrial-derived peptide. Improves metabolic function, increases insulin sensitivity, supports longevity. Regulates mitochondrial function and metabolic homeostasis.', 'A mitochondrial-derived peptide.', 'Improves metabolic function, increases insulin sensitivity, supports longevity.', 'Regulates mitochondrial function and metabolic homeostasis.', 43, 0, '10mg', 'Lyophilized powder / Injectable'),
('MOTS-C 40mg', 'mots-c-40mg', 'Weight Loss / Metabolic', 'A mitochondrial-derived peptide. Improves metabolic function, increases insulin sensitivity, supports longevity. Regulates mitochondrial function and metabolic homeostasis.', 'A mitochondrial-derived peptide.', 'Improves metabolic function, increases insulin sensitivity, supports longevity.', 'Regulates mitochondrial function and metabolic homeostasis.', 143, 0, '40mg', 'Lyophilized powder / Injectable'),
('MT-1 10mg', 'mt-1-10mg', 'Beauty / Tanning', 'Melanotan I is a synthetic analog of alpha-MSH. Researched for gradual tanning support and potential photoprotective effects for the skin. Stimulates melanocortin receptors on melanocytes, increasing melanin production with less impact on appetite or libido than MT-2.', 'Melanotan I is a synthetic analog of alpha-MSH.', 'Researched for gradual tanning support and potential photoprotective effects for the skin.', 'Stimulates melanocortin receptors on melanocytes, increasing melanin production with less impact on appetite or libido than MT-2.', 36, 0, '10mg', 'Lyophilized powder / Injectable'),
('MT-2 10mg', 'mt-2-10mg', 'Beauty / Tanning', 'Melanotan II is a more potent melanocortin analog than MT-1. Investigated for rapid tanning effects and increased libido in some users. Activates melanocortin receptors that drive melanin production and can also influence sexual arousal pathways.', 'Melanotan II is a more potent melanocortin analog than MT-1.', 'Investigated for rapid tanning effects and increased libido in some users.', 'Activates melanocortin receptors that drive melanin production and can also influence sexual arousal pathways.', 32, 0, '10mg', 'Lyophilized powder / Injectable'),
('NAD 1000mg', 'nad-1000mg', 'General Health', 'A coenzyme found in all living cells, crucial for energy metabolism. Boosts cellular energy, supports mitochondrial function, enhances cognitive performance, anti-aging potential. Involved in redox reactions and activates sirtuins, which regulate aging and metabolism.', 'A coenzyme found in all living cells, crucial for energy metabolism.', 'Boosts cellular energy, supports mitochondrial function, enhances cognitive performance, anti-aging potential.', 'Involved in redox reactions and activates sirtuins, which regulate aging and metabolism.', 171, 0, '1000mg', 'Lyophilized powder / Injectable'),
('NAD 500mg', 'nad-500mg', 'General Health', 'A coenzyme found in all living cells, crucial for energy metabolism. Boosts cellular energy, supports mitochondrial function, enhances cognitive performance, anti-aging potential. Involved in redox reactions and activates sirtuins, which regulate aging and metabolism.', 'A coenzyme found in all living cells, crucial for energy metabolism.', 'Boosts cellular energy, supports mitochondrial function, enhances cognitive performance, anti-aging potential.', 'Involved in redox reactions and activates sirtuins, which regulate aging and metabolism.', 107, 0, '500mg', 'Lyophilized powder / Injectable'),
('Oxytocin 10iu', 'oxytocin-10iu', 'Sexual Health', 'A natural hormone and peptide. Improves bonding, trust, reduces stress, supports sexual health. Binds to oxytocin receptors influencing emotional and social behavior.', 'A natural hormone and peptide.', 'Improves bonding, trust, reduces stress, supports sexual health.', 'Binds to oxytocin receptors influencing emotional and social behavior.', 45, 0, '10iu', 'Lyophilized powder / Injectable'),
('P21 5mg', 'p21-5mg', 'Cognitive / Focus', 'A research peptide associated with neuroprotection and cognitive support. Explored for improving learning, memory, and resistance to neurodegenerative processes. Believed to act on neuronal growth and synaptic plasticity pathways, although mechanisms remain under investigation.', 'A research peptide associated with neuroprotection and cognitive support.', 'Explored for improving learning, memory, and resistance to neurodegenerative processes.', 'Believed to act on neuronal growth and synaptic plasticity pathways, although mechanisms remain under investigation.', 71, 0, '5mg', 'Lyophilized powder / Injectable'),
('PEG-MGF 2mg', 'peg-mgf-2mg', 'Bodybuilding / Fitness', 'Modified version of MGF with extended half-life. Sustained muscle growth and recovery effects. Extended activation of muscle satellite cells for repair and hypertrophy.', 'Modified version of MGF with extended half-life.', 'Sustained muscle growth and recovery effects.', 'Extended activation of muscle satellite cells for repair and hypertrophy.', 45, 0, '2mg', 'Lyophilized powder / Injectable'),
('Pinealon 10mg', 'pinealon-10mg', 'Cognitive / Focus', 'Pinealon is a short tri-peptide associated with brain and metabolic support. Used in research for memory support, mental clarity, and regulation of carbohydrate and lipid metabolism. Believed to act at the level of gene expression in neurons, supporting protein synthesis and neuroprotection.', 'Pinealon is a short tri-peptide associated with brain and metabolic support.', 'Used in research for memory support, mental clarity, and regulation of carbohydrate and lipid metabolism.', 'Believed to act at the level of gene expression in neurons, supporting protein synthesis and neuroprotection.', 57, 0, '10mg', 'Lyophilized powder / Injectable'),
('PNC-27 5mg', 'pnc-27-5mg', 'General Health', 'An experimental peptide studied for its potential selective action on cancer cells. Investigated in preclinical models for promoting tumor cell death without affecting healthy tissue. Targets specific mitochondrial membrane components on malignant cells, triggering apoptosis in research settings.', 'An experimental peptide studied for its potential selective action on cancer cells.', 'Investigated in preclinical models for promoting tumor cell death without affecting healthy tissue.', 'Targets specific mitochondrial membrane components on malignant cells, triggering apoptosis in research settings.', 35, 0, '5mg', 'Lyophilized powder / Injectable'),
('PT-141 10mg', 'pt-141-10mg', 'Sexual Health', 'Also known as Bremelanotide, derived from Melanotan II. Improves sexual function and libido in both men and women. Activates melanocortin receptors involved in arousal pathways.', 'Also known as Bremelanotide, derived from Melanotan II.', 'Improves sexual function and libido in both men and women.', 'Activates melanocortin receptors involved in arousal pathways.', 36, 0, '10mg', 'Lyophilized powder / Injectable'),
('Retatrutide 10mg', 'retatrutide-10mg', 'Weight Loss / Metabolic', 'A novel investigational GLP-1/GIP/glucagon receptor agonist. Supports weight loss, improves insulin sensitivity, potential in obesity management. Activates multiple incretin pathways, enhancing satiety and metabolic regulation.', 'A novel investigational GLP-1/GIP/glucagon receptor agonist.', 'Supports weight loss, improves insulin sensitivity, potential in obesity management.', 'Activates multiple incretin pathways, enhancing satiety and metabolic regulation.', 107, 0, '10mg', 'Lyophilized powder / Injectable'),
('Retatrutide 20mg', 'retatrutide-20mg', 'Weight Loss / Metabolic', 'A novel investigational GLP-1/GIP/glucagon receptor agonist. Supports weight loss, improves insulin sensitivity, potential in obesity management. Activates multiple incretin pathways, enhancing satiety and metabolic regulation.', 'A novel investigational GLP-1/GIP/glucagon receptor agonist.', 'Supports weight loss, improves insulin sensitivity, potential in obesity management.', 'Activates multiple incretin pathways, enhancing satiety and metabolic regulation.', 200, 0, '20mg', 'Lyophilized powder / Injectable'),
('Retatrutide 30mg', 'retatrutide-30mg', 'Weight Loss / Metabolic', 'A novel investigational GLP-1/GIP/glucagon receptor agonist. Supports weight loss, improves insulin sensitivity, potential in obesity management. Activates multiple incretin pathways, enhancing satiety and metabolic regulation.', 'A novel investigational GLP-1/GIP/glucagon receptor agonist.', 'Supports weight loss, improves insulin sensitivity, potential in obesity management.', 'Activates multiple incretin pathways, enhancing satiety and metabolic regulation.', 257, 0, '30mg', 'Lyophilized powder / Injectable'),
('Retatrutide 40mg', 'retatrutide-40mg', 'Weight Loss / Metabolic', 'A novel investigational GLP-1/GIP/glucagon receptor agonist. Supports weight loss, improves insulin sensitivity, potential in obesity management. Activates multiple incretin pathways, enhancing satiety and metabolic regulation.', 'A novel investigational GLP-1/GIP/glucagon receptor agonist.', 'Supports weight loss, improves insulin sensitivity, potential in obesity management.', 'Activates multiple incretin pathways, enhancing satiety and metabolic regulation.', 314, 0, '40mg', 'Lyophilized powder / Injectable'),
('Retatrutide 50mg', 'retatrutide-50mg', 'Weight Loss / Metabolic', 'A novel investigational GLP-1/GIP/glucagon receptor agonist. Supports weight loss, improves insulin sensitivity, potential in obesity management. Activates multiple incretin pathways, enhancing satiety and metabolic regulation.', 'A novel investigational GLP-1/GIP/glucagon receptor agonist.', 'Supports weight loss, improves insulin sensitivity, potential in obesity management.', 'Activates multiple incretin pathways, enhancing satiety and metabolic regulation.', 357, 0, '50mg', 'Lyophilized powder / Injectable'),
('Selank 10mg', 'selank-10mg', 'Cognitive / Focus', 'A synthetic peptide derived from Tuftsin. Reduces anxiety, improves mood, enhances learning and memory. Regulates neurotransmitters such as serotonin and dopamine.', 'A synthetic peptide derived from Tuftsin.', 'Reduces anxiety, improves mood, enhances learning and memory.', 'Regulates neurotransmitters such as serotonin and dopamine.', 32, 0, '10mg', 'Lyophilized powder / Injectable'),
('Semaglutide 2.5mg', 'semaglutide-2-5mg', 'Weight Loss / Metabolic', 'A GLP-1 receptor agonist peptide originally developed for type 2 diabetes and obesity. Supports significant weight loss, improved blood sugar control, and reduced appetite in clinical settings. Mimics the incretin hormone GLP-1, slowing gastric emptying, enhancing insulin secretion, and reducing hunger signals.', 'A GLP-1 receptor agonist peptide originally developed for type 2 diabetes and obesity.', 'Supports significant weight loss, improved blood sugar control, and reduced appetite in clinical settings.', 'Mimics the incretin hormone GLP-1, slowing gastric emptying, enhancing insulin secretion, and reducing hunger signals.', 71, 0, '2.5mg', 'Lyophilized powder / Injectable'),
('Semax 10mg', 'semax-10mg', 'Cognitive / Focus', 'A synthetic peptide with nootropic properties. Enhances focus, memory, reduces anxiety, neuroprotection. Modulates brain-derived neurotrophic factor (BDNF) and dopamine pathways.', 'A synthetic peptide with nootropic properties.', 'Enhances focus, memory, reduces anxiety, neuroprotection.', 'Modulates brain-derived neurotrophic factor (BDNF) and dopamine pathways.', 29, 0, '10mg', 'Lyophilized powder / Injectable'),
('SLU-PP-332 5mg', 'slu-pp-332-5mg', 'Weight Loss / Metabolic', 'Investigational peptide for muscle and metabolism regulation. Potential muscle enhancement, improved metabolic function. Acts through pathways modulating protein synthesis and energy balance.', 'Investigational peptide for muscle and metabolism regulation.', 'Potential muscle enhancement, improved metabolic function.', 'Acts through pathways modulating protein synthesis and energy balance.', 100, 0, '5mg', 'Lyophilized powder / Injectable'),
('SS-31 10mg', 'ss-31-10mg', 'Cognitive / Focus', 'A mitochondrial-targeted antioxidant peptide. Protects against oxidative stress, supports energy production, anti-aging potential. Binds to cardiolipin in mitochondria, reducing reactive oxygen species (ROS).', 'A mitochondrial-targeted antioxidant peptide.', 'Protects against oxidative stress, supports energy production, anti-aging potential.', 'Binds to cardiolipin in mitochondria, reducing reactive oxygen species (ROS).', 54, 0, '10mg', 'Lyophilized powder / Injectable'),
('TB500 10mg', 'tb500-10mg', 'Healing / Recovery', 'A synthetic version of Thymosin Beta-4, a natural healing peptide. Speeds recovery from injury, reduces inflammation, promotes muscle regeneration. Regulates actin, a protein essential for cell movement and repair processes.', 'A synthetic version of Thymosin Beta-4, a natural healing peptide.', 'Speeds recovery from injury, reduces inflammation, promotes muscle regeneration.', 'Regulates actin, a protein essential for cell movement and repair processes.', 71, 0, '10mg', 'Lyophilized powder / Injectable'),
('TB500 5mg', 'tb500-5mg', 'Healing / Recovery', 'A synthetic version of Thymosin Beta-4, a natural healing peptide. Speeds recovery from injury, reduces inflammation, promotes muscle regeneration. Regulates actin, a protein essential for cell movement and repair processes.', 'A synthetic version of Thymosin Beta-4, a natural healing peptide.', 'Speeds recovery from injury, reduces inflammation, promotes muscle regeneration.', 'Regulates actin, a protein essential for cell movement and repair processes.', 43, 0, '5mg', 'Lyophilized powder / Injectable'),
('Tesamorelin 10mg', 'tesamorelin-10mg', 'Bodybuilding / Fitness', 'A synthetic analog of growth hormone-releasing hormone (GHRH). Stimulates natural growth hormone production, reduces visceral fat, supports lean muscle. Binds to pituitary receptors, triggering release of growth hormone.', 'A synthetic analog of growth hormone-releasing hormone (GHRH).', 'Stimulates natural growth hormone production, reduces visceral fat, supports lean muscle.', 'Binds to pituitary receptors, triggering release of growth hormone.', 129, 0, '10mg', 'Lyophilized powder / Injectable'),
('Tesamorelin 5mg', 'tesamorelin-5mg', 'Bodybuilding / Fitness', 'A synthetic analog of growth hormone-releasing hormone (GHRH). Stimulates natural growth hormone production, reduces visceral fat, supports lean muscle. Binds to pituitary receptors, triggering release of growth hormone.', 'A synthetic analog of growth hormone-releasing hormone (GHRH).', 'Stimulates natural growth hormone production, reduces visceral fat, supports lean muscle.', 'Binds to pituitary receptors, triggering release of growth hormone.', 71, 0, '5mg', 'Lyophilized powder / Injectable'),
('Thymalin 10mg', 'thymalin-10mg', 'General Health', 'Thymic peptide extract. Supports immune function, anti-aging potential, regeneration support. Modulates T-cell development and immune signaling.', 'Thymic peptide extract.', 'Supports immune function, anti-aging potential, regeneration support.', 'Modulates T-cell development and immune signaling.', 75, 0, '10mg', 'Lyophilized powder / Injectable'),
('Tirzepatide 10mg', 'tirzepatide-10mg', 'Weight Loss / Metabolic', 'Dual GLP-1 and GIP receptor agonist. Significant weight reduction, improved glucose control, cardiovascular support. Enhances insulin secretion, delays gastric emptying, reduces appetite.', 'Dual GLP-1 and GIP receptor agonist.', 'Significant weight reduction, improved glucose control, cardiovascular support.', 'Enhances insulin secretion, delays gastric emptying, reduces appetite.', 107, 0, '10mg', 'Lyophilized powder / Injectable'),
('Tirzepatide 20mg', 'tirzepatide-20mg', 'Weight Loss / Metabolic', 'Dual GLP-1 and GIP receptor agonist. Significant weight reduction, improved glucose control, cardiovascular support. Enhances insulin secretion, delays gastric emptying, reduces appetite.', 'Dual GLP-1 and GIP receptor agonist.', 'Significant weight reduction, improved glucose control, cardiovascular support.', 'Enhances insulin secretion, delays gastric emptying, reduces appetite.', 200, 0, '20mg', 'Lyophilized powder / Injectable'),
('Tirzepatide 30mg', 'tirzepatide-30mg', 'Weight Loss / Metabolic', 'Dual GLP-1 and GIP receptor agonist. Significant weight reduction, improved glucose control, cardiovascular support. Enhances insulin secretion, delays gastric emptying, reduces appetite.', 'Dual GLP-1 and GIP receptor agonist.', 'Significant weight reduction, improved glucose control, cardiovascular support.', 'Enhances insulin secretion, delays gastric emptying, reduces appetite.', 257, 0, '30mg', 'Lyophilized powder / Injectable'),
('Tirzepatide 40mg', 'tirzepatide-40mg', 'Weight Loss / Metabolic', 'Dual GLP-1 and GIP receptor agonist. Significant weight reduction, improved glucose control, cardiovascular support. Enhances insulin secretion, delays gastric emptying, reduces appetite.', 'Dual GLP-1 and GIP receptor agonist.', 'Significant weight reduction, improved glucose control, cardiovascular support.', 'Enhances insulin secretion, delays gastric emptying, reduces appetite.', 300, 0, '40mg', 'Lyophilized powder / Injectable'),
('VIP 10mg', 'vip-10mg', 'General Health', 'Vasoactive intestinal peptide. Neuroprotective, improves circulation, supports immune modulation. Acts as a neurotransmitter and vasodilator, regulating immune and vascular tone.', 'Vasoactive intestinal peptide.', 'Neuroprotective, improves circulation, supports immune modulation.', 'Acts as a neurotransmitter and vasodilator, regulating immune and vascular tone.', 86, 0, '10mg', 'Lyophilized powder / Injectable');
