-- Northern Peptides - Update Products Table
-- Run this in Supabase SQL Editor

-- Step 1: Delete placeholder products
DELETE FROM products;

-- Step 2: Add new columns for richer product data
ALTER TABLE products ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS description_short TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS benefits TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS mechanism TEXT;

-- Step 3: Create unique index on slug
CREATE UNIQUE INDEX IF NOT EXISTS idx_products_slug ON products(slug);

-- Step 4: Insert all 67 products from your Excel file
INSERT INTO products (name, slug, category, description, description_short, benefits, mechanism, price, stock_quantity, strength, form, purity, featured, active) VALUES
('5-Amino 10mg', '5-amino-10mg', 'Weight Loss / Metabolic', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways. May support fat loss, metabolic health, and body recomposition in research settings. Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways.', 'May support fat loss, metabolic health, and body recomposition in research settings.', 'Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 57, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('5-Amino 50mg', '5-amino-50mg', 'Weight Loss / Metabolic', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways. May support fat loss, metabolic health, and body recomposition in research settings. Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways.', 'May support fat loss, metabolic health, and body recomposition in research settings.', 'Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 143, 0, '50mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('5-Amino 5mg', '5-amino-5mg', 'Weight Loss / Metabolic', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways. May support fat loss, metabolic health, and body recomposition in research settings. Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 'A research peptide often referenced as 5-Amino-1MQ, targeting cellular metabolism pathways.', 'May support fat loss, metabolic health, and body recomposition in research settings.', 'Believed to influence NNMT-related pathways, potentially improving energy expenditure and lipid metabolism.', 57, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('ACE-031 1mg', 'ace-031-1mg', 'Bodybuilding / Fitness', 'A myostatin inhibitor peptide. Promotes muscle growth, strength enhancement, potential in muscle-wasting diseases. Blocks myostatin, a protein that inhibits muscle development.', 'A myostatin inhibitor peptide.', 'Promotes muscle growth, strength enhancement, potential in muscle-wasting diseases.', 'Blocks myostatin, a protein that inhibits muscle development.', 130, 0, '1mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Adipotide 10mg', 'adipotide-10mg', 'Weight Loss / Metabolic', 'ADIPOTIDE is a research peptide used in advanced protocols. It is explored for potential benefits in performance, recovery, and metabolic support. Its mechanisms are still being studied and it should be considered for research use only.', 'ADIPOTIDE is a research peptide used in advanced protocols.', 'It is explored for potential benefits in performance, recovery, and metabolic support.', 'Its mechanisms are still being studied and it should be considered for research use only.', 60, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('AICAR 50mg', 'aicar-50mg', 'Weight Loss / Metabolic', 'An AMP-activated protein kinase (AMPK) activator. Mimics exercise effects, enhances endurance, supports fat metabolism. Activates AMPK, promoting glucose uptake and fatty acid oxidation.', 'An AMP-activated protein kinase (AMPK) activator.', 'Mimics exercise effects, enhances endurance, supports fat metabolism.', 'Activates AMPK, promoting glucose uptake and fatty acid oxidation.', 150, 0, '50mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('AOD9604 10mg', 'aod9604-10mg', 'Weight Loss / Metabolic', 'Fragment of human growth hormone. Fat burning, weight management, supports cartilage repair. Stimulates lipolysis without significantly affecting blood sugar or growth.', 'Fragment of human growth hormone.', 'Fat burning, weight management, supports cartilage repair.', 'Stimulates lipolysis without significantly affecting blood sugar or growth.', 71, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('AOD9604 5mg', 'aod9604-5mg', 'Weight Loss / Metabolic', 'Fragment of human growth hormone. Fat burning, weight management, supports cartilage repair. Stimulates lipolysis without significantly affecting blood sugar or growth.', 'Fragment of human growth hormone.', 'Fat burning, weight management, supports cartilage repair.', 'Stimulates lipolysis without significantly affecting blood sugar or growth.', 43, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('ARA-290 10mg', 'ara-290-10mg', 'General Health', 'A peptide analog of erythropoietin-derived sequences with tissue-protective properties. Investigated for neuropathic pain relief, anti-inflammatory effects, and organ protection. Acts on the innate repair receptor (IRR), modulating inflammatory signaling and promoting tissue repair without stimulating red blood cell production.', 'A peptide analog of erythropoietin-derived sequences with tissue-protective properties.', 'Investigated for neuropathic pain relief, anti-inflammatory effects, and organ protection.', 'Acts on the innate repair receptor (IRR), modulating inflammatory signaling and promoting tissue repair without stimulating red blood cell production.', 50, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('BPC+ TB500 10mg', 'bpc-tb500-10mg', 'Healing / Recovery', 'A combination of BPC-157 and TB-500 formulated for intensive healing support. Used in research for accelerated recovery from soft-tissue injuries, tendon and ligament support, and reduced inflammation. Combines angiogenesis- and cell-migration–supporting pathways of both peptides to enhance tissue regeneration.', 'A combination of BPC-157 and TB-500 formulated for intensive healing support.', 'Used in research for accelerated recovery from soft-tissue injuries, tendon and ligament support, and reduced inflammation.', 'Combines angiogenesis- and cell-migration–supporting pathways of both peptides to enhance tissue regeneration.', 68, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('BPC+ TB500 20mg', 'bpc-tb500-20mg', 'Healing / Recovery', 'A combination of BPC-157 and TB-500 formulated for intensive healing support. Used in research for accelerated recovery from soft-tissue injuries, tendon and ligament support, and reduced inflammation. Combines angiogenesis- and cell-migration–supporting pathways of both peptides to enhance tissue regeneration.', 'A combination of BPC-157 and TB-500 formulated for intensive healing support.', 'Used in research for accelerated recovery from soft-tissue injuries, tendon and ligament support, and reduced inflammation.', 'Combines angiogenesis- and cell-migration–supporting pathways of both peptides to enhance tissue regeneration.', 107, 0, '20mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('BPC-157 10mg', 'bpc-157-10mg', 'Healing / Recovery', 'A synthetic peptide derived from gastric proteins. Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health. Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 'A synthetic peptide derived from gastric proteins.', 'Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health.', 'Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 57, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('BPC-157 20mg', 'bpc-157-20mg', 'Healing / Recovery', 'A synthetic peptide derived from gastric proteins. Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health. Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 'A synthetic peptide derived from gastric proteins.', 'Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health.', 'Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 98, 0, '20mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('BPC-157 5mg', 'bpc-157-5mg', 'Healing / Recovery', 'A synthetic peptide derived from gastric proteins. Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health. Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 'A synthetic peptide derived from gastric proteins.', 'Accelerates wound healing, reduces inflammation, supports tendon and ligament repair, may improve gut health.', 'Enhances angiogenesis (formation of new blood vessels) and modulates growth factors involved in tissue repair.', 32, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('Cagrilintide 2.4mg', 'cagrilintide-2-4mg', 'Weight Loss / Metabolic', 'Amylin analog developed for obesity management. Weight loss, appetite control, metabolic health improvement. Activates amylin receptors, enhancing satiety and glucose regulation.', 'Amylin analog developed for obesity management.', 'Weight loss, appetite control, metabolic health improvement.', 'Activates amylin receptors, enhancing satiety and glucose regulation.', 120, 0, '2.4mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('CJC-1295 with DAC 5mg', 'cjc-1295-dac-5mg', 'Bodybuilding / Fitness', 'A long-acting synthetic analog of growth hormone-releasing hormone (GHRH). Provides stable GH release over days, improves recovery, supports lean muscle growth, enhances fat metabolism. Binds to pituitary receptors and maintains prolonged GH release due to Drug Affinity Complex (DAC) technology.', 'A long-acting synthetic analog of growth hormone-releasing hormone (GHRH).', 'Provides stable GH release over days, improves recovery, supports lean muscle growth, enhances fat metabolism.', 'Binds to pituitary receptors and maintains prolonged GH release due to Drug Affinity Complex (DAC) technology.', 54, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('CJC-1295 without DAC + IPA 5mg', 'cjc-1295-ipa-5mg', 'Bodybuilding / Fitness', 'A synergistic blend of CJC-1295 and Ipamorelin. Maximizes GH secretion, enhances recovery, supports lean mass gain, fat burning, and cellular repair. CJC-1295 stimulates GH release while Ipamorelin selectively enhances it without significant cortisol increase.', 'A synergistic blend of CJC-1295 and Ipamorelin.', 'Maximizes GH secretion, enhances recovery, supports lean mass gain, fat burning, and cellular repair.', 'CJC-1295 stimulates GH release while Ipamorelin selectively enhances it without significant cortisol increase.', 57, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('CJC-1295 without DAC 5mg', 'cjc-1295-no-dac-5mg', 'Bodybuilding / Fitness', 'A shorter-acting version of CJC-1295, also a GHRH analog. Stimulates natural GH release in a pulsatile manner, supports muscle growth and fat loss, improves sleep quality. Triggers pituitary GH release but with a shorter half-life, mimicking natural hormone rhythms.', 'A shorter-acting version of CJC-1295, also a GHRH analog.', 'Stimulates natural GH release in a pulsatile manner, supports muscle growth and fat loss, improves sleep quality.', 'Triggers pituitary GH release but with a shorter half-life, mimicking natural hormone rhythms.', 50, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('DSIP 5mg', 'dsip-5mg', 'Cognitive / Focus', 'Delta Sleep-Inducing Peptide. Improves sleep quality, reduces stress, supports hormone regulation. Regulates sleep-wake cycles and influences pituitary hormone release.', 'Delta Sleep-Inducing Peptide.', 'Improves sleep quality, reduces stress, supports hormone regulation.', 'Regulates sleep-wake cycles and influences pituitary hormone release.', 35, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Epithalon 50mg', 'epithalon-50mg', 'Anti-Aging / Beauty', 'A synthetic tetrapeptide related to telomerase activation. Anti-aging, promotes cellular longevity, supports hormonal balance. May activate telomerase, helping maintain telomere length and cellular health.', 'A synthetic tetrapeptide related to telomerase activation.', 'Anti-aging, promotes cellular longevity, supports hormonal balance.', 'May activate telomerase, helping maintain telomere length and cellular health.', 100, 0, '50mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('Epitalon 10mg', 'epitalon-10mg', 'Anti-Aging / Beauty', 'A synthetic tetrapeptide related to telomerase activation. Anti-aging, promotes cellular longevity, supports hormonal balance. May activate telomerase, helping maintain telomere length and cellular health.', 'A synthetic tetrapeptide related to telomerase activation.', 'Anti-aging, promotes cellular longevity, supports hormonal balance.', 'May activate telomerase, helping maintain telomere length and cellular health.', 35, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Follistatin 344 1mg', 'follistatin-344-1mg', 'Bodybuilding / Fitness', 'A glycoprotein peptide that inhibits myostatin. Increases muscle mass, may improve strength, supports body recomposition. Binds to myostatin, preventing muscle-growth inhibition.', 'A glycoprotein peptide that inhibits myostatin.', 'Increases muscle mass, may improve strength, supports body recomposition.', 'Binds to myostatin, preventing muscle-growth inhibition.', 140, 0, '1mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Follistatin 315 1mg', 'follistatin-315-1mg', 'Bodybuilding / Fitness', 'Another follistatin variant known for localized muscle effects. Targeted muscle growth, minimal systemic effects, potential for site-specific enhancement. Focuses myostatin inhibition more locally, reducing off-target influence.', 'Another follistatin variant known for localized muscle effects.', 'Targeted muscle growth, minimal systemic effects, potential for site-specific enhancement.', 'Focuses myostatin inhibition more locally, reducing off-target influence.', 160, 0, '1mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Fragment 176-191 5mg', 'fragment-176-191-5mg', 'Weight Loss / Metabolic', 'The fat-burning fragment of HGH. Enhances fat loss, supports metabolic efficiency, minimal effect on insulin sensitivity. Directly triggers lipolysis in fat cells without other growth-related effects of HGH.', 'The fat-burning fragment of HGH.', 'Enhances fat loss, supports metabolic efficiency, minimal effect on insulin sensitivity.', 'Directly triggers lipolysis in fat cells without other growth-related effects of HGH.', 45, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('GHK-Cu 200mg', 'ghk-cu-200mg', 'Anti-Aging / Beauty', 'A copper peptide complex renowned for skin and tissue repair. Skin rejuvenation, wound healing, anti-inflammatory, hair growth support. Activates collagen synthesis, promotes ECM remodeling, and has antioxidant effects.', 'A copper peptide complex renowned for skin and tissue repair.', 'Skin rejuvenation, wound healing, anti-inflammatory, hair growth support.', 'Activates collagen synthesis, promotes ECM remodeling, and has antioxidant effects.', 85, 0, '200mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('GHK-Cu 50mg', 'ghk-cu-50mg', 'Anti-Aging / Beauty', 'A copper peptide complex renowned for skin and tissue repair. Skin rejuvenation, wound healing, anti-inflammatory, hair growth support. Activates collagen synthesis, promotes ECM remodeling, and has antioxidant effects.', 'A copper peptide complex renowned for skin and tissue repair.', 'Skin rejuvenation, wound healing, anti-inflammatory, hair growth support.', 'Activates collagen synthesis, promotes ECM remodeling, and has antioxidant effects.', 48, 0, '50mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('GHRP-2 10mg', 'ghrp-2-10mg', 'Bodybuilding / Fitness', 'A growth hormone releasing peptide. Stimulates GH release, increases appetite, supports muscle growth and fat reduction. Activates ghrelin receptors in the pituitary, boosting GH secretion.', 'A growth hormone releasing peptide.', 'Stimulates GH release, increases appetite, supports muscle growth and fat reduction.', 'Activates ghrelin receptors in the pituitary, boosting GH secretion.', 32, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('GHRP-2 5mg', 'ghrp-2-5mg', 'Bodybuilding / Fitness', 'A growth hormone releasing peptide. Stimulates GH release, increases appetite, supports muscle growth and fat reduction. Activates ghrelin receptors in the pituitary, boosting GH secretion.', 'A growth hormone releasing peptide.', 'Stimulates GH release, increases appetite, supports muscle growth and fat reduction.', 'Activates ghrelin receptors in the pituitary, boosting GH secretion.', 23, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('GHRP-6 10mg', 'ghrp-6-10mg', 'Bodybuilding / Fitness', 'Another GH releasing peptide with strong appetite-stimulating effects. Enhanced GH release, increased hunger, improved recovery. Similar mechanism to GHRP-2 but more pronounced appetite effect.', 'Another GH releasing peptide with strong appetite-stimulating effects.', 'Enhanced GH release, increased hunger, improved recovery.', 'Similar mechanism to GHRP-2 but more pronounced appetite effect.', 32, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('GHRP-6 5mg', 'ghrp-6-5mg', 'Bodybuilding / Fitness', 'Another GH releasing peptide with strong appetite-stimulating effects. Enhanced GH release, increased hunger, improved recovery. Similar mechanism to GHRP-2 but more pronounced appetite effect.', 'Another GH releasing peptide with strong appetite-stimulating effects.', 'Enhanced GH release, increased hunger, improved recovery.', 'Similar mechanism to GHRP-2 but more pronounced appetite effect.', 23, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Gonadorelin 2mg', 'gonadorelin-2mg', 'Hormonal / Fertility', 'A synthetic GnRH (gonadotropin-releasing hormone). Stimulates LH and FSH release, supports fertility research, hormone regulation. Acts on the pituitary to release gonadotropins, influencing reproductive hormone levels.', 'A synthetic GnRH (gonadotropin-releasing hormone).', 'Stimulates LH and FSH release, supports fertility research, hormone regulation.', 'Acts on the pituitary to release gonadotropins, influencing reproductive hormone levels.', 25, 0, '2mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Hexarelin 5mg', 'hexarelin-5mg', 'Bodybuilding / Fitness', 'A potent GH secretagogue peptide. Strong GH release, improved cardiac function, increased strength. Binds to ghrelin receptors strongly, producing robust GH pulses.', 'A potent GH secretagogue peptide.', 'Strong GH release, improved cardiac function, increased strength.', 'Binds to ghrelin receptors strongly, producing robust GH pulses.', 35, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('HGH Fragment 176-191 10mg', 'hgh-fragment-176-191-10mg', 'Weight Loss / Metabolic', 'A larger quantity variant of the lipolytic HGH fragment. Enhanced fat loss, metabolic support, may help reduce stubborn fat deposits. Same mechanism as Fragment 176-191, targeting fat cells for breakdown.', 'A larger quantity variant of the lipolytic HGH fragment.', 'Enhanced fat loss, metabolic support, may help reduce stubborn fat deposits.', 'Same mechanism as Fragment 176-191, targeting fat cells for breakdown.', 80, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('IGF-1 DES 1mg', 'igf-1-des-1mg', 'Bodybuilding / Fitness', 'A truncated form of IGF-1 with potent anabolic properties. Localized muscle growth, enhanced cell proliferation, supports tissue repair. Lacks the binding protein domain, allowing rapid, localized action.', 'A truncated form of IGF-1 with potent anabolic properties.', 'Localized muscle growth, enhanced cell proliferation, supports tissue repair.', 'Lacks the binding protein domain, allowing rapid, localized action.', 85, 0, '1mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('IGF-1 LR3 1mg', 'igf-1-lr3-1mg', 'Bodybuilding / Fitness', 'A modified IGF-1 with extended half-life. Prolonged anabolic effect, muscle hypertrophy, enhanced nutrient uptake. Reduced IGF-1 binding protein affinity means longer systemic action.', 'A modified IGF-1 with extended half-life.', 'Prolonged anabolic effect, muscle hypertrophy, enhanced nutrient uptake.', 'Reduced IGF-1 binding protein affinity means longer systemic action.', 95, 0, '1mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Ipamorelin 5mg', 'ipamorelin-5mg', 'Bodybuilding / Fitness', 'A selective GH secretagogue. Clean GH release without major cortisol or prolactin spikes, supports recovery, anti-aging, lean mass. Specifically targets GH release without broadly affecting other hormones.', 'A selective GH secretagogue.', 'Clean GH release without major cortisol or prolactin spikes, supports recovery, anti-aging, lean mass.', 'Specifically targets GH release without broadly affecting other hormones.', 38, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('Kisspeptin-10 5mg', 'kisspeptin-10-5mg', 'Hormonal / Fertility', 'A peptide involved in reproductive hormone signaling. Stimulates GnRH release, supports fertility, studied in reproductive health contexts. Triggers GnRH secretion, influencing downstream LH and FSH.', 'A peptide involved in reproductive hormone signaling.', 'Stimulates GnRH release, supports fertility, studied in reproductive health contexts.', 'Triggers GnRH secretion, influencing downstream LH and FSH.', 40, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('LL-37 5mg', 'll-37-5mg', 'General Health', 'An antimicrobial peptide derived from cathelicidin. Immune support, wound healing, antimicrobial properties. Disrupts microbial membranes and modulates immune responses.', 'An antimicrobial peptide derived from cathelicidin.', 'Immune support, wound healing, antimicrobial properties.', 'Disrupts microbial membranes and modulates immune responses.', 75, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Melanotan I 10mg', 'melanotan-i-10mg', 'Beauty / Tanning', 'A melanocortin receptor agonist. Tanning without UV, potential photoprotection, studied for skin conditions. Stimulates melanin production by activating MC1R receptors.', 'A melanocortin receptor agonist.', 'Tanning without UV, potential photoprotection, studied for skin conditions.', 'Stimulates melanin production by activating MC1R receptors.', 35, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Melanotan II 10mg', 'melanotan-ii-10mg', 'Beauty / Tanning', 'A more potent melanocortin analog. Enhanced tanning, potential libido increase, appetite suppression. Acts on multiple melanocortin receptors, influencing pigmentation and sexual function.', 'A more potent melanocortin analog.', 'Enhanced tanning, potential libido increase, appetite suppression.', 'Acts on multiple melanocortin receptors, influencing pigmentation and sexual function.', 28, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('MGF (IGF-1Ec) 5mg', 'mgf-5mg', 'Bodybuilding / Fitness', 'Mechano Growth Factor, a splice variant of IGF-1. Muscle repair, local growth stimulus, supports recovery post-exercise. Activated by muscle damage, initiating satellite cell proliferation.', 'Mechano Growth Factor, a splice variant of IGF-1.', 'Muscle repair, local growth stimulus, supports recovery post-exercise.', 'Activated by muscle damage, initiating satellite cell proliferation.', 60, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('MK-677 25mg/mL (30mL)', 'mk-677-liquid', 'Bodybuilding / Fitness', 'An oral GH secretagogue (not a peptide but often grouped similarly). Increased GH and IGF-1, improved sleep, supports muscle and recovery. Mimics ghrelin to stimulate GH release without injections.', 'An oral GH secretagogue (not a peptide but often grouped similarly).', 'Increased GH and IGF-1, improved sleep, supports muscle and recovery.', 'Mimics ghrelin to stimulate GH release without injections.', 80, 0, '25mg/mL', 'Liquid / Oral', '99%+', true, true),
('Modafinil 30ct x 200mg', 'modafinil-30ct', 'Cognitive / Focus', 'MODAFINIL is a compound used for cognitive support and wakefulness. It is explored for potential benefits in alertness, focus, and productivity. Its exact mechanism involves modulation of neurotransmitter systems related to the sleep-wake cycle.', 'MODAFINIL is a compound used for cognitive support and wakefulness.', 'It is explored for potential benefits in alertness, focus, and productivity.', 'Its exact mechanism involves modulation of neurotransmitter systems related to the sleep-wake cycle.', 80, 0, '200mg x 30', 'Tablet / Oral', '99%+', false, true),
('NAD+ 500mg', 'nad-500mg', 'Anti-Aging / Beauty', 'Nicotinamide adenine dinucleotide precursor. Supports cellular energy, anti-aging research, metabolic health. Boosts NAD+ levels, crucial for mitochondrial function and sirtuins.', 'Nicotinamide adenine dinucleotide precursor.', 'Supports cellular energy, anti-aging research, metabolic health.', 'Boosts NAD+ levels, crucial for mitochondrial function and sirtuins.', 100, 0, '500mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('Oxytocin 5mg', 'oxytocin-5mg', 'Hormonal / Fertility', 'The bonding and social hormone peptide. Social behavior research, may enhance trust and bonding. Acts on oxytocin receptors in the brain and reproductive system.', 'The bonding and social hormone peptide.', 'Social behavior research, may enhance trust and bonding.', 'Acts on oxytocin receptors in the brain and reproductive system.', 40, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('PEG-MGF 5mg', 'peg-mgf-5mg', 'Bodybuilding / Fitness', 'PEGylated Mechano Growth Factor for extended action. Longer-lasting muscle repair and growth stimulus, improved stability. PEGylation extends half-life, providing sustained release.', 'PEGylated Mechano Growth Factor for extended action.', 'Longer-lasting muscle repair and growth stimulus, improved stability.', 'PEGylation extends half-life, providing sustained release.', 75, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Pentadecapeptide BPC 157 Arginine Salt Form 10mg', 'bpc-157-arginine-10mg', 'Healing / Recovery', 'An arginine salt variant of BPC-157 known for enhanced stability. Improved healing, stable formulation, supports gut and musculoskeletal health. Same tissue-repair mechanism as BPC-157, potentially improved stability.', 'An arginine salt variant of BPC-157 known for enhanced stability.', 'Improved healing, stable formulation, supports gut and musculoskeletal health.', 'Same tissue-repair mechanism as BPC-157, potentially improved stability.', 65, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('PT-141 10mg', 'pt-141-10mg', 'Sexual Health', 'Bremelanotide, a melanocortin-based peptide for sexual dysfunction research. Enhances sexual desire in both men and women, potential treatment for sexual dysfunction. Activates melanocortin receptors in the brain influencing sexual arousal pathways.', 'Bremelanotide, a melanocortin-based peptide for sexual dysfunction research.', 'Enhances sexual desire in both men and women, potential treatment for sexual dysfunction.', 'Activates melanocortin receptors in the brain influencing sexual arousal pathways.', 45, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('Retatrutide 4mg', 'retatrutide-4mg', 'Weight Loss / Metabolic', 'A triple agonist peptide (GLP-1, GIP, glucagon receptor). Significant weight loss, improved metabolic markers, blood sugar regulation. Engages multiple incretin pathways for enhanced metabolic effects.', 'A triple agonist peptide (GLP-1, GIP, glucagon receptor).', 'Significant weight loss, improved metabolic markers, blood sugar regulation.', 'Engages multiple incretin pathways for enhanced metabolic effects.', 150, 0, '4mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('Selank 10mg', 'selank-10mg', 'Cognitive / Focus', 'A Russian nootropic peptide. Anxiolytic, cognitive enhancement, immune modulation. Modulates GABA and serotonin systems, reducing anxiety and improving focus.', 'A Russian nootropic peptide.', 'Anxiolytic, cognitive enhancement, immune modulation.', 'Modulates GABA and serotonin systems, reducing anxiety and improving focus.', 40, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Selank 5mg', 'selank-5mg', 'Cognitive / Focus', 'A Russian nootropic peptide. Anxiolytic, cognitive enhancement, immune modulation. Modulates GABA and serotonin systems, reducing anxiety and improving focus.', 'A Russian nootropic peptide.', 'Anxiolytic, cognitive enhancement, immune modulation.', 'Modulates GABA and serotonin systems, reducing anxiety and improving focus.', 25, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Semax 30mg', 'semax-30mg', 'Cognitive / Focus', 'A nootropic peptide derived from ACTH. Cognitive enhancement, neuroprotection, improved memory. Influences BDNF and other neurotrophic factors, supporting brain plasticity.', 'A nootropic peptide derived from ACTH.', 'Cognitive enhancement, neuroprotection, improved memory.', 'Influences BDNF and other neurotrophic factors, supporting brain plasticity.', 50, 0, '30mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('Semaglutide 10mg', 'semaglutide-10mg', 'Weight Loss / Metabolic', 'A GLP-1 receptor agonist. Powerful weight loss, improved glycemic control, appetite suppression. Mimics GLP-1, regulating appetite, insulin, and gastric emptying.', 'A GLP-1 receptor agonist.', 'Powerful weight loss, improved glycemic control, appetite suppression.', 'Mimics GLP-1, regulating appetite, insulin, and gastric emptying.', 175, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('Semaglutide 5mg', 'semaglutide-5mg', 'Weight Loss / Metabolic', 'A GLP-1 receptor agonist. Powerful weight loss, improved glycemic control, appetite suppression. Mimics GLP-1, regulating appetite, insulin, and gastric emptying.', 'A GLP-1 receptor agonist.', 'Powerful weight loss, improved glycemic control, appetite suppression.', 'Mimics GLP-1, regulating appetite, insulin, and gastric emptying.', 100, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Sermorelin 5mg', 'sermorelin-5mg', 'Bodybuilding / Fitness', 'A GHRH analog for stimulating natural GH release. Natural GH release stimulation, anti-aging support, improved sleep. Binds to GHRH receptors, mimicking natural signaling.', 'A GHRH analog for stimulating natural GH release.', 'Natural GH release stimulation, anti-aging support, improved sleep.', 'Binds to GHRH receptors, mimicking natural signaling.', 40, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Snap-8 200mg', 'snap-8-200mg', 'Anti-Aging / Beauty', 'An acetyl octapeptide-3 used in skincare. Reduces wrinkles, smooths expression lines, supports youthful appearance. Inhibits SNARE complex formation, reducing muscle contractions that cause wrinkles.', 'An acetyl octapeptide-3 used in skincare.', 'Reduces wrinkles, smooths expression lines, supports youthful appearance.', 'Inhibits SNARE complex formation, reducing muscle contractions that cause wrinkles.', 65, 0, '200mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('SS-31 (Elamipretide) 50mg', 'ss-31-50mg', 'Anti-Aging / Beauty', 'A mitochondrial-targeted peptide. Supports mitochondrial function, cellular energy, potential anti-aging and cardioprotective effects. Targets cardiolipin in mitochondrial membranes, improving energy production.', 'A mitochondrial-targeted peptide.', 'Supports mitochondrial function, cellular energy, potential anti-aging and cardioprotective effects.', 'Targets cardiolipin in mitochondrial membranes, improving energy production.', 150, 0, '50mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('TB-500 10mg', 'tb-500-10mg', 'Healing / Recovery', 'Thymosin Beta-4 derivative for tissue repair. Accelerated wound healing, reduced inflammation, improved flexibility. Promotes cell migration and blood vessel formation, enhancing tissue regeneration.', 'Thymosin Beta-4 derivative for tissue repair.', 'Accelerated wound healing, reduced inflammation, improved flexibility.', 'Promotes cell migration and blood vessel formation, enhancing tissue regeneration.', 65, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('TB-500 20mg', 'tb-500-20mg', 'Healing / Recovery', 'Thymosin Beta-4 derivative for tissue repair. Accelerated wound healing, reduced inflammation, improved flexibility. Promotes cell migration and blood vessel formation, enhancing tissue regeneration.', 'Thymosin Beta-4 derivative for tissue repair.', 'Accelerated wound healing, reduced inflammation, improved flexibility.', 'Promotes cell migration and blood vessel formation, enhancing tissue regeneration.', 100, 0, '20mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('TB-500 5mg', 'tb-500-5mg', 'Healing / Recovery', 'Thymosin Beta-4 derivative for tissue repair. Accelerated wound healing, reduced inflammation, improved flexibility. Promotes cell migration and blood vessel formation, enhancing tissue regeneration.', 'Thymosin Beta-4 derivative for tissue repair.', 'Accelerated wound healing, reduced inflammation, improved flexibility.', 'Promotes cell migration and blood vessel formation, enhancing tissue regeneration.', 40, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Tesamorelin 5mg', 'tesamorelin-5mg', 'Bodybuilding / Fitness', 'A GHRH analog FDA-approved for HIV-related lipodystrophy. Reduces visceral fat, supports GH release, may improve body composition. Stimulates pituitary GH release, particularly effective for abdominal fat reduction.', 'A GHRH analog FDA-approved for HIV-related lipodystrophy.', 'Reduces visceral fat, supports GH release, may improve body composition.', 'Stimulates pituitary GH release, particularly effective for abdominal fat reduction.', 60, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Thymosin Alpha-1 10mg', 'thymosin-alpha-1-10mg', 'General Health', 'An immune-modulating peptide from the thymus. Immune support, potential antiviral and anticancer properties. Enhances T-cell function and modulates immune responses.', 'An immune-modulating peptide from the thymus.', 'Immune support, potential antiviral and anticancer properties.', 'Enhances T-cell function and modulates immune responses.', 55, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Tirzepatide 10mg', 'tirzepatide-10mg', 'Weight Loss / Metabolic', 'A dual GLP-1 and GIP receptor agonist. Exceptional weight loss, improved metabolic markers, glycemic control. Engages two incretin pathways for enhanced satiety and metabolic improvement.', 'A dual GLP-1 and GIP receptor agonist.', 'Exceptional weight loss, improved metabolic markers, glycemic control.', 'Engages two incretin pathways for enhanced satiety and metabolic improvement.', 175, 0, '10mg', 'Lyophilized powder / Injectable', '99%+', true, true),
('Tirzepatide 15mg', 'tirzepatide-15mg', 'Weight Loss / Metabolic', 'A dual GLP-1 and GIP receptor agonist. Exceptional weight loss, improved metabolic markers, glycemic control. Engages two incretin pathways for enhanced satiety and metabolic improvement.', 'A dual GLP-1 and GIP receptor agonist.', 'Exceptional weight loss, improved metabolic markers, glycemic control.', 'Engages two incretin pathways for enhanced satiety and metabolic improvement.', 225, 0, '15mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('Tirzepatide 5mg', 'tirzepatide-5mg', 'Weight Loss / Metabolic', 'A dual GLP-1 and GIP receptor agonist. Exceptional weight loss, improved metabolic markers, glycemic control. Engages two incretin pathways for enhanced satiety and metabolic improvement.', 'A dual GLP-1 and GIP receptor agonist.', 'Exceptional weight loss, improved metabolic markers, glycemic control.', 'Engages two incretin pathways for enhanced satiety and metabolic improvement.', 100, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true),
('VIP 5mg', 'vip-5mg', 'General Health', 'Vasoactive Intestinal Peptide. Anti-inflammatory, supports gut and immune health, potential neuroprotective. Binds to VPAC receptors, influencing vascular tone, immune regulation, and neuroprotection.', 'Vasoactive Intestinal Peptide.', 'Anti-inflammatory, supports gut and immune health, potential neuroprotective.', 'Binds to VPAC receptors, influencing vascular tone, immune regulation, and neuroprotection.', 80, 0, '5mg', 'Lyophilized powder / Injectable', '99%+', false, true);
